# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/royal state/PycharmProjects/Arduino-Oscilloscope/src/MainWindowFrontEnd.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1015, 830)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1015, 830))
        MainWindow.setMaximumSize(QtCore.QSize(1015, 830))
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 590, 1011, 16))
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.MeterCheck = QtWidgets.QGroupBox(self.centralwidget)
        self.MeterCheck.setGeometry(QtCore.QRect(10, 610, 201, 51))
        self.MeterCheck.setCheckable(True)
        self.MeterCheck.setChecked(False)
        self.MeterCheck.setObjectName("MeterCheck")
        self.label_11 = QtWidgets.QLabel(self.MeterCheck)
        self.label_11.setGeometry(QtCore.QRect(10, 10, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_11.setObjectName("label_11")
        self.SignelGenCheck = QtWidgets.QGroupBox(self.centralwidget)
        self.SignelGenCheck.setGeometry(QtCore.QRect(220, 610, 191, 131))
        self.SignelGenCheck.setCheckable(True)
        self.SignelGenCheck.setChecked(False)
        self.SignelGenCheck.setObjectName("SignelGenCheck")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.SignelGenCheck)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.SigGenFreqSlider = QtWidgets.QSlider(self.SignelGenCheck)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SigGenFreqSlider.sizePolicy().hasHeightForWidth())
        self.SigGenFreqSlider.setSizePolicy(sizePolicy)
        self.SigGenFreqSlider.setMinimumSize(QtCore.QSize(119, 0))
        self.SigGenFreqSlider.setMinimum(125)
        self.SigGenFreqSlider.setMaximum(10000)
        self.SigGenFreqSlider.setPageStep(1)
        self.SigGenFreqSlider.setProperty("value", 125)
        self.SigGenFreqSlider.setOrientation(QtCore.Qt.Horizontal)
        self.SigGenFreqSlider.setObjectName("SigGenFreqSlider")
        self.horizontalLayout_9.addWidget(self.SigGenFreqSlider)
        self.SigGenFreqLabel = QtWidgets.QLabel(self.SignelGenCheck)
        self.SigGenFreqLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.SigGenFreqLabel.setObjectName("SigGenFreqLabel")
        self.horizontalLayout_9.addWidget(self.SigGenFreqLabel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.SigGenPeriodSlider = QtWidgets.QSlider(self.SignelGenCheck)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SigGenPeriodSlider.sizePolicy().hasHeightForWidth())
        self.SigGenPeriodSlider.setSizePolicy(sizePolicy)
        self.SigGenPeriodSlider.setMinimumSize(QtCore.QSize(119, 0))
        self.SigGenPeriodSlider.setMinimum(100)
        self.SigGenPeriodSlider.setMaximum(8000000)
        self.SigGenPeriodSlider.setPageStep(10)
        self.SigGenPeriodSlider.setProperty("value", 20000)
        self.SigGenPeriodSlider.setOrientation(QtCore.Qt.Horizontal)
        self.SigGenPeriodSlider.setObjectName("SigGenPeriodSlider")
        self.horizontalLayout_10.addWidget(self.SigGenPeriodSlider)
        self.SigGenPeriodLabel = QtWidgets.QLabel(self.SignelGenCheck)
        self.SigGenPeriodLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.SigGenPeriodLabel.setObjectName("SigGenPeriodLabel")
        self.horizontalLayout_10.addWidget(self.SigGenPeriodLabel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.SigGenDutyslider = QtWidgets.QSlider(self.SignelGenCheck)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SigGenDutyslider.sizePolicy().hasHeightForWidth())
        self.SigGenDutyslider.setSizePolicy(sizePolicy)
        self.SigGenDutyslider.setMinimumSize(QtCore.QSize(119, 0))
        self.SigGenDutyslider.setMinimum(0)
        self.SigGenDutyslider.setMaximum(100)
        self.SigGenDutyslider.setPageStep(1)
        self.SigGenDutyslider.setProperty("value", 25)
        self.SigGenDutyslider.setOrientation(QtCore.Qt.Horizontal)
        self.SigGenDutyslider.setObjectName("SigGenDutyslider")
        self.horizontalLayout_11.addWidget(self.SigGenDutyslider)
        self.SigGenDutyLabel = QtWidgets.QLabel(self.SignelGenCheck)
        self.SigGenDutyLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.SigGenDutyLabel.setObjectName("SigGenDutyLabel")
        self.horizontalLayout_11.addWidget(self.SigGenDutyLabel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.SamplingControlsFrame = QtWidgets.QGroupBox(self.centralwidget)
        self.SamplingControlsFrame.setGeometry(QtCore.QRect(420, 612, 231, 131))
        self.SamplingControlsFrame.setObjectName("SamplingControlsFrame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.SamplingControlsFrame)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.SampConrolDTScale = QtWidgets.QSlider(self.SamplingControlsFrame)
        self.SampConrolDTScale.setMinimum(1)
        self.SampConrolDTScale.setMaximum(100)
        self.SampConrolDTScale.setOrientation(QtCore.Qt.Horizontal)
        self.SampConrolDTScale.setObjectName("SampConrolDTScale")
        self.horizontalLayout_12.addWidget(self.SampConrolDTScale)
        self.SampConrolDTLabel = QtWidgets.QLabel(self.SamplingControlsFrame)
        self.SampConrolDTLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.SampConrolDTLabel.setObjectName("SampConrolDTLabel")
        self.horizontalLayout_12.addWidget(self.SampConrolDTLabel)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.SampControlQScale = QtWidgets.QSlider(self.SamplingControlsFrame)
        self.SampControlQScale.setMinimum(1)
        self.SampControlQScale.setMaximum(100)
        self.SampControlQScale.setProperty("value", 100)
        self.SampControlQScale.setOrientation(QtCore.Qt.Horizontal)
        self.SampControlQScale.setObjectName("SampControlQScale")
        self.horizontalLayout_13.addWidget(self.SampControlQScale)
        self.SampControlQLabel = QtWidgets.QLabel(self.SamplingControlsFrame)
        self.SampControlQLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.SampControlQLabel.setObjectName("SampControlQLabel")
        self.horizontalLayout_13.addWidget(self.SampControlQLabel)
        self.verticalLayout_7.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.SamplingControlOnceButton = QtWidgets.QPushButton(self.SamplingControlsFrame)
        self.SamplingControlOnceButton.setCheckable(True)
        self.SamplingControlOnceButton.setObjectName("SamplingControlOnceButton")
        self.horizontalLayout_14.addWidget(self.SamplingControlOnceButton)
        self.SamplingControlVariousButton = QtWidgets.QPushButton(self.SamplingControlsFrame)
        self.SamplingControlVariousButton.setCheckable(True)
        self.SamplingControlVariousButton.setObjectName("SamplingControlVariousButton")
        self.horizontalLayout_14.addWidget(self.SamplingControlVariousButton)
        self.SamplingControlFlowButton = QtWidgets.QPushButton(self.SamplingControlsFrame)
        self.SamplingControlFlowButton.setCheckable(True)
        self.SamplingControlFlowButton.setObjectName("SamplingControlFlowButton")
        self.horizontalLayout_14.addWidget(self.SamplingControlFlowButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_14)
        self.XYZCheck = QtWidgets.QGroupBox(self.centralwidget)
        self.XYZCheck.setGeometry(QtCore.QRect(660, 610, 171, 131))
        self.XYZCheck.setCheckable(True)
        self.XYZCheck.setChecked(False)
        self.XYZCheck.setObjectName("XYZCheck")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.XYZCheck)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.XYZ_VDivSlider = QtWidgets.QSlider(self.XYZCheck)
        self.XYZ_VDivSlider.setMinimum(1)
        self.XYZ_VDivSlider.setMaximum(100)
        self.XYZ_VDivSlider.setProperty("value", 20)
        self.XYZ_VDivSlider.setOrientation(QtCore.Qt.Horizontal)
        self.XYZ_VDivSlider.setObjectName("XYZ_VDivSlider")
        self.horizontalLayout_16.addWidget(self.XYZ_VDivSlider)
        self.XYZ_VDivLabel = QtWidgets.QLabel(self.XYZCheck)
        self.XYZ_VDivLabel.setObjectName("XYZ_VDivLabel")
        self.horizontalLayout_16.addWidget(self.XYZ_VDivLabel)
        self.verticalLayout_5.addLayout(self.horizontalLayout_16)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.XYZ_ViewchannelsCheck = QtWidgets.QRadioButton(self.XYZCheck)
        self.XYZ_ViewchannelsCheck.setObjectName("XYZ_ViewchannelsCheck")
        self.verticalLayout_4.addWidget(self.XYZ_ViewchannelsCheck)
        self.XYZ_SoftCurvesLabel = QtWidgets.QRadioButton(self.XYZCheck)
        self.XYZ_SoftCurvesLabel.setObjectName("XYZ_SoftCurvesLabel")
        self.verticalLayout_4.addWidget(self.XYZ_SoftCurvesLabel)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 670, 210, 70))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setCheckable(False)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.SeePointsCheck = QtWidgets.QCheckBox(self.groupBox_4)
        self.SeePointsCheck.setObjectName("SeePointsCheck")
        self.horizontalLayout_15.addWidget(self.SeePointsCheck)
        self.DetectFreqCheck = QtWidgets.QCheckBox(self.groupBox_4)
        self.DetectFreqCheck.setObjectName("DetectFreqCheck")
        self.horizontalLayout_15.addWidget(self.DetectFreqCheck)
        self.verticalLayout_2.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.SaveDataButton = QtWidgets.QPushButton(self.groupBox_4)
        self.SaveDataButton.setAutoRepeatDelay(10)
        self.SaveDataButton.setAutoRepeatInterval(10)
        self.SaveDataButton.setObjectName("SaveDataButton")
        self.horizontalLayout_19.addWidget(self.SaveDataButton)
        self.SaveDataFileFormatCombo = QtWidgets.QComboBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SaveDataFileFormatCombo.sizePolicy().hasHeightForWidth())
        self.SaveDataFileFormatCombo.setSizePolicy(sizePolicy)
        self.SaveDataFileFormatCombo.setMaximumSize(QtCore.QSize(51, 20))
        self.SaveDataFileFormatCombo.setObjectName("SaveDataFileFormatCombo")
        self.SaveDataFileFormatCombo.addItem("")
        self.SaveDataFileFormatCombo.addItem("")
        self.SaveDataFileFormatCombo.addItem("")
        self.SaveDataFileFormatCombo.addItem("")
        self.horizontalLayout_19.addWidget(self.SaveDataFileFormatCombo)
        self.verticalLayout_2.addLayout(self.horizontalLayout_19)
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(840, 610, 161, 131))
        self.groupBox_6.setCheckable(False)
        self.groupBox_6.setChecked(False)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setContentsMargins(-1, -1, 3, -1)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.ConfSerComPortCombo = QtWidgets.QComboBox(self.groupBox_6)
        self.ConfSerComPortCombo.setMinimumSize(QtCore.QSize(80, 0))
        self.ConfSerComPortCombo.setObjectName("ConfSerComPortCombo")
        self.ConfSerComPortCombo.addItem("")
        self.horizontalLayout_17.addWidget(self.ConfSerComPortCombo)
        self.ConfSerComPortLabel = QtWidgets.QLabel(self.groupBox_6)
        self.ConfSerComPortLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ConfSerComPortLabel.setObjectName("ConfSerComPortLabel")
        self.horizontalLayout_17.addWidget(self.ConfSerComPortLabel)
        self.verticalLayout_6.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setContentsMargins(-1, -1, 3, -1)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.ConfSerBaoudRateCombo = QtWidgets.QComboBox(self.groupBox_6)
        self.ConfSerBaoudRateCombo.setMinimumSize(QtCore.QSize(80, 0))
        self.ConfSerBaoudRateCombo.setObjectName("ConfSerBaoudRateCombo")
        self.ConfSerBaoudRateCombo.addItem("")
        self.horizontalLayout_18.addWidget(self.ConfSerBaoudRateCombo)
        self.ConfSerBaoudRateLabel = QtWidgets.QLabel(self.groupBox_6)
        self.ConfSerBaoudRateLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ConfSerBaoudRateLabel.setObjectName("ConfSerBaoudRateLabel")
        self.horizontalLayout_18.addWidget(self.ConfSerBaoudRateLabel)
        self.verticalLayout_6.addLayout(self.horizontalLayout_18)
        self.ConfSerPowerButton = QtWidgets.QPushButton(self.groupBox_6)
        self.ConfSerPowerButton.setMinimumSize(QtCore.QSize(0, 31))
        self.ConfSerPowerButton.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.ConfSerPowerButton.setCheckable(True)
        self.ConfSerPowerButton.setAutoRepeatDelay(100)
        self.ConfSerPowerButton.setAutoRepeatInterval(10)
        self.ConfSerPowerButton.setObjectName("ConfSerPowerButton")
        self.verticalLayout_6.addWidget(self.ConfSerPowerButton)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(822, 2, 190, 589))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(190, 0))
        self.frame.setMaximumSize(QtCore.QSize(190, 591))
        self.frame.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setLineWidth(3)
        self.frame.setObjectName("frame")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 205, 591))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(3, 3, 6, 3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.Channel1Check = QtWidgets.QGroupBox(self.frame_2)
        self.Channel1Check.setGeometry(QtCore.QRect(0, 0, 190, 146))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Channel1Check.setFont(font)
        self.Channel1Check.setAutoFillBackground(False)
        self.Channel1Check.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 15, 19);")
        self.Channel1Check.setFlat(False)
        self.Channel1Check.setCheckable(True)
        self.Channel1Check.setObjectName("Channel1Check")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.Channel1Check)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(3, 20, 183, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.Channel1VoltsSlider = QtWidgets.QSlider(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Channel1VoltsSlider.sizePolicy().hasHeightForWidth())
        self.Channel1VoltsSlider.setSizePolicy(sizePolicy)
        self.Channel1VoltsSlider.setMinimumSize(QtCore.QSize(100, 20))
        self.Channel1VoltsSlider.setMinimum(0)
        self.Channel1VoltsSlider.setMaximum(100)
        self.Channel1VoltsSlider.setPageStep(1)
        self.Channel1VoltsSlider.setProperty("value", 54)
        self.Channel1VoltsSlider.setOrientation(QtCore.Qt.Horizontal)
        self.Channel1VoltsSlider.setObjectName("Channel1VoltsSlider")
        self.horizontalLayout.addWidget(self.Channel1VoltsSlider)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.Channel1VLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Channel1VLabel.sizePolicy().hasHeightForWidth())
        self.Channel1VLabel.setSizePolicy(sizePolicy)
        self.Channel1VLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.Channel1VLabel.setObjectName("Channel1VLabel")
        self.horizontalLayout.addWidget(self.Channel1VLabel)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.Channel1Check)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(3, 50, 184, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.Channel1MsSlider = QtWidgets.QSlider(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Channel1MsSlider.sizePolicy().hasHeightForWidth())
        self.Channel1MsSlider.setSizePolicy(sizePolicy)
        self.Channel1MsSlider.setMinimumSize(QtCore.QSize(100, 20))
        self.Channel1MsSlider.setMinimum(0)
        self.Channel1MsSlider.setMaximum(100)
        self.Channel1MsSlider.setPageStep(1)
        self.Channel1MsSlider.setProperty("value", 36)
        self.Channel1MsSlider.setOrientation(QtCore.Qt.Horizontal)
        self.Channel1MsSlider.setObjectName("Channel1MsSlider")
        self.horizontalLayout_2.addWidget(self.Channel1MsSlider)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.Channel1MsLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Channel1MsLabel.sizePolicy().hasHeightForWidth())
        self.Channel1MsLabel.setSizePolicy(sizePolicy)
        self.Channel1MsLabel.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.Channel1MsLabel.setObjectName("Channel1MsLabel")
        self.horizontalLayout_2.addWidget(self.Channel1MsLabel)
        self.layoutWidget1 = QtWidgets.QWidget(self.Channel1Check)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 90, 156, 36))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 3, 0, 3)
        self.gridLayout.setHorizontalSpacing(2)
        self.gridLayout.setVerticalSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.Channel1MeasureButton = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Channel1MeasureButton.sizePolicy().hasHeightForWidth())
        self.Channel1MeasureButton.setSizePolicy(sizePolicy)
        self.Channel1MeasureButton.setMinimumSize(QtCore.QSize(0, 30))
        self.Channel1MeasureButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Channel1MeasureButton.setCheckable(True)
        self.Channel1MeasureButton.setObjectName("Channel1MeasureButton")
        self.gridLayout.addWidget(self.Channel1MeasureButton, 0, 0, 1, 1)
        self.Channel1CurveButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.Channel1CurveButton.setMinimumSize(QtCore.QSize(0, 30))
        self.Channel1CurveButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Channel1CurveButton.setCheckable(True)
        self.Channel1CurveButton.setObjectName("Channel1CurveButton")
        self.gridLayout.addWidget(self.Channel1CurveButton, 0, 1, 1, 1)
        self.Channel1TriggerButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.Channel1TriggerButton.setMinimumSize(QtCore.QSize(0, 30))
        self.Channel1TriggerButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Channel1TriggerButton.setCheckable(True)
        self.Channel1TriggerButton.setDefault(False)
        self.Channel1TriggerButton.setFlat(False)
        self.Channel1TriggerButton.setObjectName("Channel1TriggerButton")
        self.gridLayout.addWidget(self.Channel1TriggerButton, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.frame_2)
        self.Channel2Check = QtWidgets.QGroupBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Channel2Check.setFont(font)
        self.Channel2Check.setAutoFillBackground(False)
        self.Channel2Check.setStyleSheet("background-color: rgb(91, 255, 83);\n"
"color: rgb(54, 54, 54);\n"
"gridline-color: rgb(143, 143, 143);\n"
"")
        self.Channel2Check.setFlat(False)
        self.Channel2Check.setCheckable(True)
        self.Channel2Check.setObjectName("Channel2Check")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.Channel2Check)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(3, 20, 181, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.Channel2VoltsSlider = QtWidgets.QSlider(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Channel2VoltsSlider.sizePolicy().hasHeightForWidth())
        self.Channel2VoltsSlider.setSizePolicy(sizePolicy)
        self.Channel2VoltsSlider.setMinimumSize(QtCore.QSize(100, 20))
        self.Channel2VoltsSlider.setMinimum(1)
        self.Channel2VoltsSlider.setMaximum(100)
        self.Channel2VoltsSlider.setPageStep(1)
        self.Channel2VoltsSlider.setProperty("value", 54)
        self.Channel2VoltsSlider.setOrientation(QtCore.Qt.Horizontal)
        self.Channel2VoltsSlider.setObjectName("Channel2VoltsSlider")
        self.horizontalLayout_3.addWidget(self.Channel2VoltsSlider)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.Channel2VLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Channel2VLabel.sizePolicy().hasHeightForWidth())
        self.Channel2VLabel.setSizePolicy(sizePolicy)
        self.Channel2VLabel.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.Channel2VLabel.setObjectName("Channel2VLabel")
        self.horizontalLayout_3.addWidget(self.Channel2VLabel)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.Channel2Check)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(3, 50, 182, 31))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem6 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.Channel2MsSlider = QtWidgets.QSlider(self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Channel2MsSlider.sizePolicy().hasHeightForWidth())
        self.Channel2MsSlider.setSizePolicy(sizePolicy)
        self.Channel2MsSlider.setMinimumSize(QtCore.QSize(100, 20))
        self.Channel2MsSlider.setMinimum(0)
        self.Channel2MsSlider.setMaximum(100)
        self.Channel2MsSlider.setPageStep(1)
        self.Channel2MsSlider.setProperty("value", 36)
        self.Channel2MsSlider.setOrientation(QtCore.Qt.Horizontal)
        self.Channel2MsSlider.setObjectName("Channel2MsSlider")
        self.horizontalLayout_4.addWidget(self.Channel2MsSlider)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.Channel2MsLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Channel2MsLabel.sizePolicy().hasHeightForWidth())
        self.Channel2MsLabel.setSizePolicy(sizePolicy)
        self.Channel2MsLabel.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.Channel2MsLabel.setObjectName("Channel2MsLabel")
        self.horizontalLayout_4.addWidget(self.Channel2MsLabel)
        self.layoutWidget2 = QtWidgets.QWidget(self.Channel2Check)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 90, 156, 36))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_2.setContentsMargins(0, 3, 0, 3)
        self.gridLayout_2.setHorizontalSpacing(2)
        self.gridLayout_2.setVerticalSpacing(1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Channel2MeasureButton = QtWidgets.QPushButton(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Channel2MeasureButton.sizePolicy().hasHeightForWidth())
        self.Channel2MeasureButton.setSizePolicy(sizePolicy)
        self.Channel2MeasureButton.setMinimumSize(QtCore.QSize(0, 30))
        self.Channel2MeasureButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Channel2MeasureButton.setCheckable(True)
        self.Channel2MeasureButton.setObjectName("Channel2MeasureButton")
        self.gridLayout_2.addWidget(self.Channel2MeasureButton, 0, 0, 1, 1)
        self.Channel2CurveButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.Channel2CurveButton.setMinimumSize(QtCore.QSize(0, 30))
        self.Channel2CurveButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Channel2CurveButton.setCheckable(True)
        self.Channel2CurveButton.setObjectName("Channel2CurveButton")
        self.gridLayout_2.addWidget(self.Channel2CurveButton, 0, 1, 1, 1)
        self.Channel2TriggerButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.Channel2TriggerButton.setMinimumSize(QtCore.QSize(0, 30))
        self.Channel2TriggerButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Channel2TriggerButton.setCheckable(True)
        self.Channel2TriggerButton.setDefault(False)
        self.Channel2TriggerButton.setFlat(False)
        self.Channel2TriggerButton.setObjectName("Channel2TriggerButton")
        self.gridLayout_2.addWidget(self.Channel2TriggerButton, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.Channel2Check)
        self.Channel3Check = QtWidgets.QGroupBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Channel3Check.setFont(font)
        self.Channel3Check.setAutoFillBackground(False)
        self.Channel3Check.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 255);")
        self.Channel3Check.setFlat(False)
        self.Channel3Check.setCheckable(True)
        self.Channel3Check.setObjectName("Channel3Check")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.Channel3Check)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(3, 20, 181, 31))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem8 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.Channel3VoltsSlider = QtWidgets.QSlider(self.horizontalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Channel3VoltsSlider.sizePolicy().hasHeightForWidth())
        self.Channel3VoltsSlider.setSizePolicy(sizePolicy)
        self.Channel3VoltsSlider.setMinimumSize(QtCore.QSize(100, 20))
        self.Channel3VoltsSlider.setMinimum(1)
        self.Channel3VoltsSlider.setMaximum(100)
        self.Channel3VoltsSlider.setPageStep(1)
        self.Channel3VoltsSlider.setProperty("value", 54)
        self.Channel3VoltsSlider.setOrientation(QtCore.Qt.Horizontal)
        self.Channel3VoltsSlider.setObjectName("Channel3VoltsSlider")
        self.horizontalLayout_5.addWidget(self.Channel3VoltsSlider)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem9)
        self.Channel3VLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Channel3VLabel.sizePolicy().hasHeightForWidth())
        self.Channel3VLabel.setSizePolicy(sizePolicy)
        self.Channel3VLabel.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.Channel3VLabel.setObjectName("Channel3VLabel")
        self.horizontalLayout_5.addWidget(self.Channel3VLabel)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.Channel3Check)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(3, 50, 182, 31))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem10 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem10)
        self.Channel3MsSlider = QtWidgets.QSlider(self.horizontalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Channel3MsSlider.sizePolicy().hasHeightForWidth())
        self.Channel3MsSlider.setSizePolicy(sizePolicy)
        self.Channel3MsSlider.setMinimumSize(QtCore.QSize(100, 20))
        self.Channel3MsSlider.setMinimum(0)
        self.Channel3MsSlider.setMaximum(100)
        self.Channel3MsSlider.setPageStep(1)
        self.Channel3MsSlider.setProperty("value", 36)
        self.Channel3MsSlider.setOrientation(QtCore.Qt.Horizontal)
        self.Channel3MsSlider.setObjectName("Channel3MsSlider")
        self.horizontalLayout_6.addWidget(self.Channel3MsSlider)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem11)
        self.Channel3MsLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Channel3MsLabel.sizePolicy().hasHeightForWidth())
        self.Channel3MsLabel.setSizePolicy(sizePolicy)
        self.Channel3MsLabel.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.Channel3MsLabel.setObjectName("Channel3MsLabel")
        self.horizontalLayout_6.addWidget(self.Channel3MsLabel)
        self.layoutWidget_2 = QtWidgets.QWidget(self.Channel3Check)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 90, 156, 36))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 3, 0, 3)
        self.gridLayout_3.setHorizontalSpacing(2)
        self.gridLayout_3.setVerticalSpacing(1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Channel3MeasureButton = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Channel3MeasureButton.sizePolicy().hasHeightForWidth())
        self.Channel3MeasureButton.setSizePolicy(sizePolicy)
        self.Channel3MeasureButton.setMinimumSize(QtCore.QSize(0, 30))
        self.Channel3MeasureButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Channel3MeasureButton.setCheckable(True)
        self.Channel3MeasureButton.setObjectName("Channel3MeasureButton")
        self.gridLayout_3.addWidget(self.Channel3MeasureButton, 0, 0, 1, 1)
        self.Channel3CurveButton = QtWidgets.QPushButton(self.layoutWidget_2)
        self.Channel3CurveButton.setMinimumSize(QtCore.QSize(0, 30))
        self.Channel3CurveButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Channel3CurveButton.setCheckable(True)
        self.Channel3CurveButton.setObjectName("Channel3CurveButton")
        self.gridLayout_3.addWidget(self.Channel3CurveButton, 0, 1, 1, 1)
        self.Channel3TriggerButton = QtWidgets.QPushButton(self.layoutWidget_2)
        self.Channel3TriggerButton.setMinimumSize(QtCore.QSize(0, 30))
        self.Channel3TriggerButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Channel3TriggerButton.setCheckable(True)
        self.Channel3TriggerButton.setDefault(False)
        self.Channel3TriggerButton.setFlat(False)
        self.Channel3TriggerButton.setObjectName("Channel3TriggerButton")
        self.gridLayout_3.addWidget(self.Channel3TriggerButton, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.Channel3Check)
        self.Channel4Check = QtWidgets.QGroupBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Channel4Check.setFont(font)
        self.Channel4Check.setAutoFillBackground(False)
        self.Channel4Check.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"")
        self.Channel4Check.setFlat(False)
        self.Channel4Check.setCheckable(True)
        self.Channel4Check.setObjectName("Channel4Check")
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.Channel4Check)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(3, 20, 181, 31))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem12 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem12)
        self.Channel4VoltsSlider = QtWidgets.QSlider(self.horizontalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Channel4VoltsSlider.sizePolicy().hasHeightForWidth())
        self.Channel4VoltsSlider.setSizePolicy(sizePolicy)
        self.Channel4VoltsSlider.setMinimumSize(QtCore.QSize(100, 20))
        self.Channel4VoltsSlider.setMinimum(1)
        self.Channel4VoltsSlider.setMaximum(100)
        self.Channel4VoltsSlider.setPageStep(1)
        self.Channel4VoltsSlider.setProperty("value", 54)
        self.Channel4VoltsSlider.setOrientation(QtCore.Qt.Horizontal)
        self.Channel4VoltsSlider.setObjectName("Channel4VoltsSlider")
        self.horizontalLayout_7.addWidget(self.Channel4VoltsSlider)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem13)
        self.Channel4VLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Channel4VLabel.sizePolicy().hasHeightForWidth())
        self.Channel4VLabel.setSizePolicy(sizePolicy)
        self.Channel4VLabel.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.Channel4VLabel.setObjectName("Channel4VLabel")
        self.horizontalLayout_7.addWidget(self.Channel4VLabel)
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.Channel4Check)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(3, 50, 182, 31))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem14 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem14)
        self.Channel4MsSlider = QtWidgets.QSlider(self.horizontalLayoutWidget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Channel4MsSlider.sizePolicy().hasHeightForWidth())
        self.Channel4MsSlider.setSizePolicy(sizePolicy)
        self.Channel4MsSlider.setMinimumSize(QtCore.QSize(100, 20))
        self.Channel4MsSlider.setMinimum(0)
        self.Channel4MsSlider.setMaximum(100)
        self.Channel4MsSlider.setPageStep(1)
        self.Channel4MsSlider.setProperty("value", 36)
        self.Channel4MsSlider.setSliderPosition(36)
        self.Channel4MsSlider.setOrientation(QtCore.Qt.Horizontal)
        self.Channel4MsSlider.setObjectName("Channel4MsSlider")
        self.horizontalLayout_8.addWidget(self.Channel4MsSlider)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem15)
        self.Channel4MsLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Channel4MsLabel.sizePolicy().hasHeightForWidth())
        self.Channel4MsLabel.setSizePolicy(sizePolicy)
        self.Channel4MsLabel.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.Channel4MsLabel.setObjectName("Channel4MsLabel")
        self.horizontalLayout_8.addWidget(self.Channel4MsLabel)
        self.layoutWidget_3 = QtWidgets.QWidget(self.Channel4Check)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 90, 156, 36))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.gridLayout_4.setContentsMargins(0, 3, 0, 3)
        self.gridLayout_4.setHorizontalSpacing(2)
        self.gridLayout_4.setVerticalSpacing(1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.Channel4MeasureButton = QtWidgets.QPushButton(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Channel4MeasureButton.sizePolicy().hasHeightForWidth())
        self.Channel4MeasureButton.setSizePolicy(sizePolicy)
        self.Channel4MeasureButton.setMinimumSize(QtCore.QSize(0, 30))
        self.Channel4MeasureButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Channel4MeasureButton.setCheckable(True)
        self.Channel4MeasureButton.setObjectName("Channel4MeasureButton")
        self.gridLayout_4.addWidget(self.Channel4MeasureButton, 0, 0, 1, 1)
        self.Channel4CurveButton = QtWidgets.QPushButton(self.layoutWidget_3)
        self.Channel4CurveButton.setMinimumSize(QtCore.QSize(0, 30))
        self.Channel4CurveButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Channel4CurveButton.setCheckable(True)
        self.Channel4CurveButton.setObjectName("Channel4CurveButton")
        self.gridLayout_4.addWidget(self.Channel4CurveButton, 0, 1, 1, 1)
        self.Channel4TriggerButton = QtWidgets.QPushButton(self.layoutWidget_3)
        self.Channel4TriggerButton.setMinimumSize(QtCore.QSize(0, 30))
        self.Channel4TriggerButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Channel4TriggerButton.setCheckable(True)
        self.Channel4TriggerButton.setDefault(False)
        self.Channel4TriggerButton.setFlat(False)
        self.Channel4TriggerButton.setObjectName("Channel4TriggerButton")
        self.gridLayout_4.addWidget(self.Channel4TriggerButton, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.Channel4Check)
        self.Channel1GraphicsView = PlotWidget(self.centralwidget)
        self.Channel1GraphicsView.setGeometry(QtCore.QRect(3, 2, 813, 144))
        self.Channel1GraphicsView.setObjectName("Channel1GraphicsView")
        self.Channel2GraphicsView = PlotWidget(self.centralwidget)
        self.Channel2GraphicsView.setGeometry(QtCore.QRect(3, 151, 813, 143))
        self.Channel2GraphicsView.setObjectName("Channel2GraphicsView")
        self.Channel3GraphicsView = PlotWidget(self.centralwidget)
        self.Channel3GraphicsView.setGeometry(QtCore.QRect(3, 299, 813, 144))
        self.Channel3GraphicsView.setObjectName("Channel3GraphicsView")
        self.Channel4GraphicsView = PlotWidget(self.centralwidget)
        self.Channel4GraphicsView.setGeometry(QtCore.QRect(3, 448, 813, 143))
        self.Channel4GraphicsView.setObjectName("Channel4GraphicsView")
        self.layoutWidget.raise_()
        self.line.raise_()
        self.MeterCheck.raise_()
        self.SignelGenCheck.raise_()
        self.SamplingControlsFrame.raise_()
        self.XYZCheck.raise_()
        self.groupBox_4.raise_()
        self.groupBox_6.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1015, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuDemos = QtWidgets.QMenu(self.menubar)
        self.menuDemos.setObjectName("menuDemos")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setMovable(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionDemo1 = QtWidgets.QAction(MainWindow)
        self.actionDemo1.setCheckable(True)
        self.actionDemo1.setObjectName("actionDemo1")
        self.actionDemo2 = QtWidgets.QAction(MainWindow)
        self.actionDemo2.setCheckable(True)
        self.actionDemo2.setObjectName("actionDemo2")
        self.actionDemo3 = QtWidgets.QAction(MainWindow)
        self.actionDemo3.setCheckable(True)
        self.actionDemo3.setObjectName("actionDemo3")
        self.menuFile.addAction(self.actionSave)
        self.menuDemos.addAction(self.actionDemo1)
        self.menuDemos.addAction(self.actionDemo2)
        self.menuDemos.addAction(self.actionDemo3)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuDemos.menuAction())
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Arduino Oscilloscope"))
        self.MeterCheck.setTitle(_translate("MainWindow", "Meter"))
        self.label_11.setText(_translate("MainWindow", "R :: 470 ohm (1)"))
        self.SignelGenCheck.setTitle(_translate("MainWindow", "Signal Generator"))
        self.SigGenFreqLabel.setText(_translate("MainWindow", "f 50.0 Hz"))
        self.SigGenPeriodLabel.setText(_translate("MainWindow", "T 20.0 ms"))
        self.SigGenDutyLabel.setText(_translate("MainWindow", "Duty 25%"))
        self.SamplingControlsFrame.setTitle(_translate("MainWindow", "Sampling Contorls (100.0ms)"))
        self.SampConrolDTLabel.setText(_translate("MainWindow", "dt 1 ms"))
        self.SampControlQLabel.setText(_translate("MainWindow", "q 100 "))
        self.SamplingControlOnceButton.setText(_translate("MainWindow", "ONCE"))
        self.SamplingControlVariousButton.setText(_translate("MainWindow", "VARIOUS"))
        self.SamplingControlFlowButton.setText(_translate("MainWindow", "FLOW"))
        self.XYZCheck.setTitle(_translate("MainWindow", "XYZ"))
        self.XYZ_VDivLabel.setText(_translate("MainWindow", "2.0 V/Div"))
        self.XYZ_ViewchannelsCheck.setText(_translate("MainWindow", "View channels"))
        self.XYZ_SoftCurvesLabel.setText(_translate("MainWindow", "Soft Curves"))
        self.SeePointsCheck.setText(_translate("MainWindow", "See Points"))
        self.DetectFreqCheck.setText(_translate("MainWindow", "Detect Frequency"))
        self.SaveDataButton.setStatusTip(_translate("MainWindow", "Save Data to Selected File Type."))
        self.SaveDataButton.setText(_translate("MainWindow", "Save Data"))
        self.SaveDataButton.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.SaveDataFileFormatCombo.setStatusTip(_translate("MainWindow", "Select File Type to save Data to."))
        self.SaveDataFileFormatCombo.setItemText(0, _translate("MainWindow", "txt"))
        self.SaveDataFileFormatCombo.setItemText(1, _translate("MainWindow", "json"))
        self.SaveDataFileFormatCombo.setItemText(2, _translate("MainWindow", "csv"))
        self.SaveDataFileFormatCombo.setItemText(3, _translate("MainWindow", "xml"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Configure Serial"))
        self.ConfSerComPortCombo.setItemText(0, _translate("MainWindow", "COM 3"))
        self.ConfSerComPortLabel.setText(_translate("MainWindow", "COM Port"))
        self.ConfSerBaoudRateCombo.setItemText(0, _translate("MainWindow", "9600"))
        self.ConfSerBaoudRateLabel.setText(_translate("MainWindow", "Boud Rate"))
        self.ConfSerPowerButton.setText(_translate("MainWindow", "Power OFF"))
        self.Channel1Check.setTitle(_translate("MainWindow", "Channel 1"))
        self.Channel1VLabel.setText(_translate("MainWindow", "2.5 V/Div"))
        self.Channel1MsLabel.setText(_translate("MainWindow", "10.0 ms/Div"))
        self.Channel1MeasureButton.setText(_translate("MainWindow", "Measure"))
        self.Channel1CurveButton.setText(_translate("MainWindow", "Curve"))
        self.Channel1TriggerButton.setText(_translate("MainWindow", "Trigger"))
        self.Channel2Check.setTitle(_translate("MainWindow", "Channel 2"))
        self.Channel2VLabel.setText(_translate("MainWindow", "2.5 V/Div"))
        self.Channel2MsLabel.setText(_translate("MainWindow", "10.0 ms/Div"))
        self.Channel2MeasureButton.setText(_translate("MainWindow", "Measure"))
        self.Channel2CurveButton.setText(_translate("MainWindow", "Curve"))
        self.Channel2TriggerButton.setText(_translate("MainWindow", "Trigger"))
        self.Channel3Check.setTitle(_translate("MainWindow", "Channel 3"))
        self.Channel3VLabel.setText(_translate("MainWindow", "2.0 V/Div"))
        self.Channel3MsLabel.setText(_translate("MainWindow", "10.0 ms/Div"))
        self.Channel3MeasureButton.setText(_translate("MainWindow", "Measure"))
        self.Channel3CurveButton.setText(_translate("MainWindow", "Curve"))
        self.Channel3TriggerButton.setText(_translate("MainWindow", "Trigger"))
        self.Channel4Check.setTitle(_translate("MainWindow", "Channel 4"))
        self.Channel4VLabel.setText(_translate("MainWindow", "2.0 V/Div"))
        self.Channel4MsLabel.setText(_translate("MainWindow", "10.0 ms/Div"))
        self.Channel4MeasureButton.setText(_translate("MainWindow", "Measure"))
        self.Channel4CurveButton.setText(_translate("MainWindow", "Curve"))
        self.Channel4TriggerButton.setText(_translate("MainWindow", "Trigger"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuDemos.setTitle(_translate("MainWindow", "Demos"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionDemo1.setText(_translate("MainWindow", "Demo1"))
        self.actionDemo2.setText(_translate("MainWindow", "Demo2"))
        self.actionDemo3.setText(_translate("MainWindow", "Demo3"))
from pyqtgraph import PlotWidget
