# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/royal state/PycharmProjects/Arduino-Oscilloscope/src/MainWindowFrontEnd.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1015, 830)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1015, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1015, 830))
        MainWindow.setDockOptions(QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(20, 600, 999, 16))
        self.line.setLineWidth(1)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(10, 10, 1001, 591))
        self.splitter.setStyleSheet(_fromUtf8("background-color: rgb(67, 67, 67);"))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.MDIWindows = QtGui.QMdiArea(self.splitter)
        self.MDIWindows.setFrameShape(QtGui.QFrame.StyledPanel)
        self.MDIWindows.setLineWidth(2)
        brush = QtGui.QBrush(QtGui.QColor(235, 235, 235))
        brush.setStyle(QtCore.Qt.Dense5Pattern)
        self.MDIWindows.setBackground(brush)
        self.MDIWindows.setActivationOrder(QtGui.QMdiArea.ActivationHistoryOrder)
        self.MDIWindows.setViewMode(QtGui.QMdiArea.SubWindowView)
        self.MDIWindows.setTabPosition(QtGui.QTabWidget.South)
        self.MDIWindows.setObjectName(_fromUtf8("MDIWindows"))
        self.frame = QtGui.QFrame(self.splitter)
        self.frame.setMinimumSize(QtCore.QSize(190, 0))
        self.frame.setMaximumSize(QtCore.QSize(190, 591))
        self.frame.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);"))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setLineWidth(3)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.layoutWidget = QtGui.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 205, 591))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(3, 3, 6, 3)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.Channel1GroupBox = QtGui.QGroupBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Channel1GroupBox.setFont(font)
        self.Channel1GroupBox.setAutoFillBackground(False)
        self.Channel1GroupBox.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 15, 19);"))
        self.Channel1GroupBox.setFlat(False)
        self.Channel1GroupBox.setCheckable(True)
        self.Channel1GroupBox.setObjectName(_fromUtf8("Channel1GroupBox"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.Channel1GroupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(3, 20, 171, 31))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.Channel1VoltsSlider = QtGui.QSlider(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Channel1VoltsSlider.sizePolicy().hasHeightForWidth())
        self.Channel1VoltsSlider.setSizePolicy(sizePolicy)
        self.Channel1VoltsSlider.setMinimumSize(QtCore.QSize(100, 20))
        self.Channel1VoltsSlider.setOrientation(QtCore.Qt.Horizontal)
        self.Channel1VoltsSlider.setObjectName(_fromUtf8("Channel1VoltsSlider"))
        self.horizontalLayout.addWidget(self.Channel1VoltsSlider)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.Channel1VLabel = QtGui.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Channel1VLabel.sizePolicy().hasHeightForWidth())
        self.Channel1VLabel.setSizePolicy(sizePolicy)
        self.Channel1VLabel.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.Channel1VLabel.setObjectName(_fromUtf8("Channel1VLabel"))
        self.horizontalLayout.addWidget(self.Channel1VLabel)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.Channel1GroupBox)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(3, 50, 184, 31))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem2 = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.Channel1MsSlider = QtGui.QSlider(self.horizontalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Channel1MsSlider.sizePolicy().hasHeightForWidth())
        self.Channel1MsSlider.setSizePolicy(sizePolicy)
        self.Channel1MsSlider.setMinimumSize(QtCore.QSize(100, 20))
        self.Channel1MsSlider.setOrientation(QtCore.Qt.Horizontal)
        self.Channel1MsSlider.setObjectName(_fromUtf8("Channel1MsSlider"))
        self.horizontalLayout_2.addWidget(self.Channel1MsSlider)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.Channel1MsLabel = QtGui.QLabel(self.horizontalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Channel1MsLabel.sizePolicy().hasHeightForWidth())
        self.Channel1MsLabel.setSizePolicy(sizePolicy)
        self.Channel1MsLabel.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.Channel1MsLabel.setObjectName(_fromUtf8("Channel1MsLabel"))
        self.horizontalLayout_2.addWidget(self.Channel1MsLabel)
        self.layoutWidget1 = QtGui.QWidget(self.Channel1GroupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 90, 156, 36))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 3, -1, 3)
        self.gridLayout.setHorizontalSpacing(2)
        self.gridLayout.setVerticalSpacing(1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.Channel1MeasureButton = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Channel1MeasureButton.sizePolicy().hasHeightForWidth())
        self.Channel1MeasureButton.setSizePolicy(sizePolicy)
        self.Channel1MeasureButton.setMinimumSize(QtCore.QSize(0, 30))
        self.Channel1MeasureButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Channel1MeasureButton.setCheckable(True)
        self.Channel1MeasureButton.setObjectName(_fromUtf8("Channel1MeasureButton"))
        self.gridLayout.addWidget(self.Channel1MeasureButton, 0, 0, 1, 1)
        self.Channel1CurveButton = QtGui.QPushButton(self.layoutWidget1)
        self.Channel1CurveButton.setMinimumSize(QtCore.QSize(0, 30))
        self.Channel1CurveButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Channel1CurveButton.setCheckable(True)
        self.Channel1CurveButton.setObjectName(_fromUtf8("Channel1CurveButton"))
        self.gridLayout.addWidget(self.Channel1CurveButton, 0, 1, 1, 1)
        self.Channel1TriggerButton = QtGui.QPushButton(self.layoutWidget1)
        self.Channel1TriggerButton.setMinimumSize(QtCore.QSize(0, 30))
        self.Channel1TriggerButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Channel1TriggerButton.setCheckable(True)
        self.Channel1TriggerButton.setDefault(False)
        self.Channel1TriggerButton.setFlat(False)
        self.Channel1TriggerButton.setObjectName(_fromUtf8("Channel1TriggerButton"))
        self.gridLayout.addWidget(self.Channel1TriggerButton, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.Channel1GroupBox)
        self.Channel2GroupBox = QtGui.QGroupBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Channel2GroupBox.setFont(font)
        self.Channel2GroupBox.setAutoFillBackground(False)
        self.Channel2GroupBox.setStyleSheet(_fromUtf8("background-color: rgb(91, 255, 83);\n"
"color: rgb(54, 54, 54);\n"
"gridline-color: rgb(143, 143, 143);\n"
""))
        self.Channel2GroupBox.setFlat(False)
        self.Channel2GroupBox.setCheckable(True)
        self.Channel2GroupBox.setObjectName(_fromUtf8("Channel2GroupBox"))
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.Channel2GroupBox)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(3, 20, 169, 31))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem4 = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.Channel2VoltsSlider = QtGui.QSlider(self.horizontalLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Channel2VoltsSlider.sizePolicy().hasHeightForWidth())
        self.Channel2VoltsSlider.setSizePolicy(sizePolicy)
        self.Channel2VoltsSlider.setMinimumSize(QtCore.QSize(100, 20))
        self.Channel2VoltsSlider.setOrientation(QtCore.Qt.Horizontal)
        self.Channel2VoltsSlider.setObjectName(_fromUtf8("Channel2VoltsSlider"))
        self.horizontalLayout_3.addWidget(self.Channel2VoltsSlider)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.Channel2VLabel = QtGui.QLabel(self.horizontalLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Channel2VLabel.sizePolicy().hasHeightForWidth())
        self.Channel2VLabel.setSizePolicy(sizePolicy)
        self.Channel2VLabel.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.Channel2VLabel.setObjectName(_fromUtf8("Channel2VLabel"))
        self.horizontalLayout_3.addWidget(self.Channel2VLabel)
        self.horizontalLayoutWidget_4 = QtGui.QWidget(self.Channel2GroupBox)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(3, 50, 182, 31))
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem6 = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.Channel2MsSlider = QtGui.QSlider(self.horizontalLayoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Channel2MsSlider.sizePolicy().hasHeightForWidth())
        self.Channel2MsSlider.setSizePolicy(sizePolicy)
        self.Channel2MsSlider.setMinimumSize(QtCore.QSize(100, 20))
        self.Channel2MsSlider.setOrientation(QtCore.Qt.Horizontal)
        self.Channel2MsSlider.setObjectName(_fromUtf8("Channel2MsSlider"))
        self.horizontalLayout_4.addWidget(self.Channel2MsSlider)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.Channel2MsLabel = QtGui.QLabel(self.horizontalLayoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Channel2MsLabel.sizePolicy().hasHeightForWidth())
        self.Channel2MsLabel.setSizePolicy(sizePolicy)
        self.Channel2MsLabel.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.Channel2MsLabel.setObjectName(_fromUtf8("Channel2MsLabel"))
        self.horizontalLayout_4.addWidget(self.Channel2MsLabel)
        self.layoutWidget2 = QtGui.QWidget(self.Channel2GroupBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 90, 156, 36))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget2)
        self.gridLayout_2.setContentsMargins(0, 3, -1, 3)
        self.gridLayout_2.setHorizontalSpacing(2)
        self.gridLayout_2.setVerticalSpacing(1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.Channel2MeasureButton = QtGui.QPushButton(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Channel2MeasureButton.sizePolicy().hasHeightForWidth())
        self.Channel2MeasureButton.setSizePolicy(sizePolicy)
        self.Channel2MeasureButton.setMinimumSize(QtCore.QSize(0, 30))
        self.Channel2MeasureButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Channel2MeasureButton.setCheckable(True)
        self.Channel2MeasureButton.setObjectName(_fromUtf8("Channel2MeasureButton"))
        self.gridLayout_2.addWidget(self.Channel2MeasureButton, 0, 0, 1, 1)
        self.Channel2CurveButton = QtGui.QPushButton(self.layoutWidget2)
        self.Channel2CurveButton.setMinimumSize(QtCore.QSize(0, 30))
        self.Channel2CurveButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Channel2CurveButton.setCheckable(True)
        self.Channel2CurveButton.setObjectName(_fromUtf8("Channel2CurveButton"))
        self.gridLayout_2.addWidget(self.Channel2CurveButton, 0, 1, 1, 1)
        self.Channel2TriggerButton = QtGui.QPushButton(self.layoutWidget2)
        self.Channel2TriggerButton.setMinimumSize(QtCore.QSize(0, 30))
        self.Channel2TriggerButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Channel2TriggerButton.setCheckable(True)
        self.Channel2TriggerButton.setDefault(False)
        self.Channel2TriggerButton.setFlat(False)
        self.Channel2TriggerButton.setObjectName(_fromUtf8("Channel2TriggerButton"))
        self.gridLayout_2.addWidget(self.Channel2TriggerButton, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.Channel2GroupBox)
        self.Channel3GroupBox = QtGui.QGroupBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Channel3GroupBox.setFont(font)
        self.Channel3GroupBox.setAutoFillBackground(False)
        self.Channel3GroupBox.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 255);"))
        self.Channel3GroupBox.setFlat(False)
        self.Channel3GroupBox.setCheckable(True)
        self.Channel3GroupBox.setObjectName(_fromUtf8("Channel3GroupBox"))
        self.horizontalLayoutWidget_5 = QtGui.QWidget(self.Channel3GroupBox)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(3, 20, 169, 31))
        self.horizontalLayoutWidget_5.setObjectName(_fromUtf8("horizontalLayoutWidget_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem8 = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.Channel3VoltsSlider = QtGui.QSlider(self.horizontalLayoutWidget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Channel3VoltsSlider.sizePolicy().hasHeightForWidth())
        self.Channel3VoltsSlider.setSizePolicy(sizePolicy)
        self.Channel3VoltsSlider.setMinimumSize(QtCore.QSize(100, 20))
        self.Channel3VoltsSlider.setOrientation(QtCore.Qt.Horizontal)
        self.Channel3VoltsSlider.setObjectName(_fromUtf8("Channel3VoltsSlider"))
        self.horizontalLayout_5.addWidget(self.Channel3VoltsSlider)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem9)
        self.Channel3VLabel = QtGui.QLabel(self.horizontalLayoutWidget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Channel3VLabel.sizePolicy().hasHeightForWidth())
        self.Channel3VLabel.setSizePolicy(sizePolicy)
        self.Channel3VLabel.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.Channel3VLabel.setObjectName(_fromUtf8("Channel3VLabel"))
        self.horizontalLayout_5.addWidget(self.Channel3VLabel)
        self.horizontalLayoutWidget_6 = QtGui.QWidget(self.Channel3GroupBox)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(3, 50, 182, 31))
        self.horizontalLayoutWidget_6.setObjectName(_fromUtf8("horizontalLayoutWidget_6"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem10 = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem10)
        self.Channel3MsSlider = QtGui.QSlider(self.horizontalLayoutWidget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Channel3MsSlider.sizePolicy().hasHeightForWidth())
        self.Channel3MsSlider.setSizePolicy(sizePolicy)
        self.Channel3MsSlider.setMinimumSize(QtCore.QSize(100, 20))
        self.Channel3MsSlider.setOrientation(QtCore.Qt.Horizontal)
        self.Channel3MsSlider.setObjectName(_fromUtf8("Channel3MsSlider"))
        self.horizontalLayout_6.addWidget(self.Channel3MsSlider)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem11)
        self.Channel3MsLabel = QtGui.QLabel(self.horizontalLayoutWidget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Channel3MsLabel.sizePolicy().hasHeightForWidth())
        self.Channel3MsLabel.setSizePolicy(sizePolicy)
        self.Channel3MsLabel.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.Channel3MsLabel.setObjectName(_fromUtf8("Channel3MsLabel"))
        self.horizontalLayout_6.addWidget(self.Channel3MsLabel)
        self.layoutWidget_2 = QtGui.QWidget(self.Channel3GroupBox)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 90, 156, 36))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 3, -1, 3)
        self.gridLayout_3.setHorizontalSpacing(2)
        self.gridLayout_3.setVerticalSpacing(1)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.Channel3MeasureButton = QtGui.QPushButton(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Channel3MeasureButton.sizePolicy().hasHeightForWidth())
        self.Channel3MeasureButton.setSizePolicy(sizePolicy)
        self.Channel3MeasureButton.setMinimumSize(QtCore.QSize(0, 30))
        self.Channel3MeasureButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Channel3MeasureButton.setCheckable(True)
        self.Channel3MeasureButton.setObjectName(_fromUtf8("Channel3MeasureButton"))
        self.gridLayout_3.addWidget(self.Channel3MeasureButton, 0, 0, 1, 1)
        self.Channel3CurveButton = QtGui.QPushButton(self.layoutWidget_2)
        self.Channel3CurveButton.setMinimumSize(QtCore.QSize(0, 30))
        self.Channel3CurveButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Channel3CurveButton.setCheckable(True)
        self.Channel3CurveButton.setObjectName(_fromUtf8("Channel3CurveButton"))
        self.gridLayout_3.addWidget(self.Channel3CurveButton, 0, 1, 1, 1)
        self.Channel3TriggerButton = QtGui.QPushButton(self.layoutWidget_2)
        self.Channel3TriggerButton.setMinimumSize(QtCore.QSize(0, 30))
        self.Channel3TriggerButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Channel3TriggerButton.setCheckable(True)
        self.Channel3TriggerButton.setDefault(False)
        self.Channel3TriggerButton.setFlat(False)
        self.Channel3TriggerButton.setObjectName(_fromUtf8("Channel3TriggerButton"))
        self.gridLayout_3.addWidget(self.Channel3TriggerButton, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.Channel3GroupBox)
        self.Channel4GroupBox = QtGui.QGroupBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Channel4GroupBox.setFont(font)
        self.Channel4GroupBox.setAutoFillBackground(False)
        self.Channel4GroupBox.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);\n"
""))
        self.Channel4GroupBox.setFlat(False)
        self.Channel4GroupBox.setCheckable(True)
        self.Channel4GroupBox.setObjectName(_fromUtf8("Channel4GroupBox"))
        self.horizontalLayoutWidget_7 = QtGui.QWidget(self.Channel4GroupBox)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(3, 20, 169, 31))
        self.horizontalLayoutWidget_7.setObjectName(_fromUtf8("horizontalLayoutWidget_7"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem12 = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem12)
        self.Channel4VoltsSlider = QtGui.QSlider(self.horizontalLayoutWidget_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Channel4VoltsSlider.sizePolicy().hasHeightForWidth())
        self.Channel4VoltsSlider.setSizePolicy(sizePolicy)
        self.Channel4VoltsSlider.setMinimumSize(QtCore.QSize(100, 20))
        self.Channel4VoltsSlider.setOrientation(QtCore.Qt.Horizontal)
        self.Channel4VoltsSlider.setObjectName(_fromUtf8("Channel4VoltsSlider"))
        self.horizontalLayout_7.addWidget(self.Channel4VoltsSlider)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem13)
        self.Channel4VLabel = QtGui.QLabel(self.horizontalLayoutWidget_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Channel4VLabel.sizePolicy().hasHeightForWidth())
        self.Channel4VLabel.setSizePolicy(sizePolicy)
        self.Channel4VLabel.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.Channel4VLabel.setObjectName(_fromUtf8("Channel4VLabel"))
        self.horizontalLayout_7.addWidget(self.Channel4VLabel)
        self.horizontalLayoutWidget_8 = QtGui.QWidget(self.Channel4GroupBox)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(3, 50, 182, 31))
        self.horizontalLayoutWidget_8.setObjectName(_fromUtf8("horizontalLayoutWidget_8"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem14 = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem14)
        self.Channel4MsSlider = QtGui.QSlider(self.horizontalLayoutWidget_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Channel4MsSlider.sizePolicy().hasHeightForWidth())
        self.Channel4MsSlider.setSizePolicy(sizePolicy)
        self.Channel4MsSlider.setMinimumSize(QtCore.QSize(100, 20))
        self.Channel4MsSlider.setOrientation(QtCore.Qt.Horizontal)
        self.Channel4MsSlider.setObjectName(_fromUtf8("Channel4MsSlider"))
        self.horizontalLayout_8.addWidget(self.Channel4MsSlider)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem15)
        self.Channel4MsLabel = QtGui.QLabel(self.horizontalLayoutWidget_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Channel4MsLabel.sizePolicy().hasHeightForWidth())
        self.Channel4MsLabel.setSizePolicy(sizePolicy)
        self.Channel4MsLabel.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.Channel4MsLabel.setObjectName(_fromUtf8("Channel4MsLabel"))
        self.horizontalLayout_8.addWidget(self.Channel4MsLabel)
        self.layoutWidget_3 = QtGui.QWidget(self.Channel4GroupBox)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 90, 156, 36))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.gridLayout_4 = QtGui.QGridLayout(self.layoutWidget_3)
        self.gridLayout_4.setContentsMargins(0, 3, -1, 3)
        self.gridLayout_4.setHorizontalSpacing(2)
        self.gridLayout_4.setVerticalSpacing(1)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.Channel4MeasureButton = QtGui.QPushButton(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Channel4MeasureButton.sizePolicy().hasHeightForWidth())
        self.Channel4MeasureButton.setSizePolicy(sizePolicy)
        self.Channel4MeasureButton.setMinimumSize(QtCore.QSize(0, 30))
        self.Channel4MeasureButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Channel4MeasureButton.setCheckable(True)
        self.Channel4MeasureButton.setObjectName(_fromUtf8("Channel4MeasureButton"))
        self.gridLayout_4.addWidget(self.Channel4MeasureButton, 0, 0, 1, 1)
        self.Channel4CurveButton = QtGui.QPushButton(self.layoutWidget_3)
        self.Channel4CurveButton.setMinimumSize(QtCore.QSize(0, 30))
        self.Channel4CurveButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Channel4CurveButton.setCheckable(True)
        self.Channel4CurveButton.setObjectName(_fromUtf8("Channel4CurveButton"))
        self.gridLayout_4.addWidget(self.Channel4CurveButton, 0, 1, 1, 1)
        self.Channel4TriggerButton = QtGui.QPushButton(self.layoutWidget_3)
        self.Channel4TriggerButton.setMinimumSize(QtCore.QSize(0, 30))
        self.Channel4TriggerButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Channel4TriggerButton.setCheckable(True)
        self.Channel4TriggerButton.setDefault(False)
        self.Channel4TriggerButton.setFlat(False)
        self.Channel4TriggerButton.setObjectName(_fromUtf8("Channel4TriggerButton"))
        self.gridLayout_4.addWidget(self.Channel4TriggerButton, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.Channel4GroupBox)
        self.MeterCheck = QtGui.QGroupBox(self.centralwidget)
        self.MeterCheck.setGeometry(QtCore.QRect(10, 610, 201, 51))
        self.MeterCheck.setCheckable(True)
        self.MeterCheck.setChecked(False)
        self.MeterCheck.setObjectName(_fromUtf8("MeterCheck"))
        self.label_11 = QtGui.QLabel(self.MeterCheck)
        self.label_11.setGeometry(QtCore.QRect(10, 10, 181, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.SignelGenCheck = QtGui.QGroupBox(self.centralwidget)
        self.SignelGenCheck.setGeometry(QtCore.QRect(220, 610, 191, 131))
        self.SignelGenCheck.setCheckable(True)
        self.SignelGenCheck.setChecked(False)
        self.SignelGenCheck.setObjectName(_fromUtf8("SignelGenCheck"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.SignelGenCheck)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.SigGenFreqSlider = QtGui.QSlider(self.SignelGenCheck)
        self.SigGenFreqSlider.setOrientation(QtCore.Qt.Horizontal)
        self.SigGenFreqSlider.setObjectName(_fromUtf8("SigGenFreqSlider"))
        self.horizontalLayout_9.addWidget(self.SigGenFreqSlider)
        self.SigGenFreqLabel = QtGui.QLabel(self.SignelGenCheck)
        self.SigGenFreqLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.SigGenFreqLabel.setObjectName(_fromUtf8("SigGenFreqLabel"))
        self.horizontalLayout_9.addWidget(self.SigGenFreqLabel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.SigGenPeriodSlider = QtGui.QSlider(self.SignelGenCheck)
        self.SigGenPeriodSlider.setOrientation(QtCore.Qt.Horizontal)
        self.SigGenPeriodSlider.setObjectName(_fromUtf8("SigGenPeriodSlider"))
        self.horizontalLayout_10.addWidget(self.SigGenPeriodSlider)
        self.SigGenPeriodLabel = QtGui.QLabel(self.SignelGenCheck)
        self.SigGenPeriodLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.SigGenPeriodLabel.setObjectName(_fromUtf8("SigGenPeriodLabel"))
        self.horizontalLayout_10.addWidget(self.SigGenPeriodLabel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.SigGenDutyslider = QtGui.QSlider(self.SignelGenCheck)
        self.SigGenDutyslider.setOrientation(QtCore.Qt.Horizontal)
        self.SigGenDutyslider.setObjectName(_fromUtf8("SigGenDutyslider"))
        self.horizontalLayout_11.addWidget(self.SigGenDutyslider)
        self.SigGenDutyLabel = QtGui.QLabel(self.SignelGenCheck)
        self.SigGenDutyLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.SigGenDutyLabel.setObjectName(_fromUtf8("SigGenDutyLabel"))
        self.horizontalLayout_11.addWidget(self.SigGenDutyLabel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.SamplingControlsFrame = QtGui.QGroupBox(self.centralwidget)
        self.SamplingControlsFrame.setGeometry(QtCore.QRect(420, 612, 231, 131))
        self.SamplingControlsFrame.setObjectName(_fromUtf8("SamplingControlsFrame"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.SamplingControlsFrame)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.SampConrolDTScale = QtGui.QSlider(self.SamplingControlsFrame)
        self.SampConrolDTScale.setOrientation(QtCore.Qt.Horizontal)
        self.SampConrolDTScale.setObjectName(_fromUtf8("SampConrolDTScale"))
        self.horizontalLayout_12.addWidget(self.SampConrolDTScale)
        self.SampConrolDTLabel = QtGui.QLabel(self.SamplingControlsFrame)
        self.SampConrolDTLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.SampConrolDTLabel.setObjectName(_fromUtf8("SampConrolDTLabel"))
        self.horizontalLayout_12.addWidget(self.SampConrolDTLabel)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.SampControlQScale = QtGui.QSlider(self.SamplingControlsFrame)
        self.SampControlQScale.setOrientation(QtCore.Qt.Horizontal)
        self.SampControlQScale.setObjectName(_fromUtf8("SampControlQScale"))
        self.horizontalLayout_13.addWidget(self.SampControlQScale)
        self.SampControlQLabel = QtGui.QLabel(self.SamplingControlsFrame)
        self.SampControlQLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.SampControlQLabel.setObjectName(_fromUtf8("SampControlQLabel"))
        self.horizontalLayout_13.addWidget(self.SampControlQLabel)
        self.verticalLayout_7.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.SamplingControlOnceButton = QtGui.QPushButton(self.SamplingControlsFrame)
        self.SamplingControlOnceButton.setCheckable(True)
        self.SamplingControlOnceButton.setObjectName(_fromUtf8("SamplingControlOnceButton"))
        self.horizontalLayout_14.addWidget(self.SamplingControlOnceButton)
        self.SamplingControlVariousButton = QtGui.QPushButton(self.SamplingControlsFrame)
        self.SamplingControlVariousButton.setCheckable(True)
        self.SamplingControlVariousButton.setObjectName(_fromUtf8("SamplingControlVariousButton"))
        self.horizontalLayout_14.addWidget(self.SamplingControlVariousButton)
        self.SamplingControlFlowButton = QtGui.QPushButton(self.SamplingControlsFrame)
        self.SamplingControlFlowButton.setCheckable(True)
        self.SamplingControlFlowButton.setObjectName(_fromUtf8("SamplingControlFlowButton"))
        self.horizontalLayout_14.addWidget(self.SamplingControlFlowButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_14)
        self.XYZCheck = QtGui.QGroupBox(self.centralwidget)
        self.XYZCheck.setGeometry(QtCore.QRect(660, 610, 171, 131))
        self.XYZCheck.setCheckable(True)
        self.XYZCheck.setChecked(False)
        self.XYZCheck.setObjectName(_fromUtf8("XYZCheck"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.XYZCheck)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.XYZ_VDivSlider = QtGui.QSlider(self.XYZCheck)
        self.XYZ_VDivSlider.setOrientation(QtCore.Qt.Horizontal)
        self.XYZ_VDivSlider.setObjectName(_fromUtf8("XYZ_VDivSlider"))
        self.horizontalLayout_16.addWidget(self.XYZ_VDivSlider)
        self.XYZ_VDivLabel = QtGui.QLabel(self.XYZCheck)
        self.XYZ_VDivLabel.setObjectName(_fromUtf8("XYZ_VDivLabel"))
        self.horizontalLayout_16.addWidget(self.XYZ_VDivLabel)
        self.verticalLayout_5.addLayout(self.horizontalLayout_16)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.XYZ_ViewchannelsCheck = QtGui.QRadioButton(self.XYZCheck)
        self.XYZ_ViewchannelsCheck.setObjectName(_fromUtf8("XYZ_ViewchannelsCheck"))
        self.verticalLayout_4.addWidget(self.XYZ_ViewchannelsCheck)
        self.XYZ_SoftCurvesLabel = QtGui.QRadioButton(self.XYZCheck)
        self.XYZ_SoftCurvesLabel.setObjectName(_fromUtf8("XYZ_SoftCurvesLabel"))
        self.verticalLayout_4.addWidget(self.XYZ_SoftCurvesLabel)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 670, 210, 68))
        self.groupBox_4.setTitle(_fromUtf8(""))
        self.groupBox_4.setCheckable(False)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.SeePointsCheck = QtGui.QCheckBox(self.groupBox_4)
        self.SeePointsCheck.setObjectName(_fromUtf8("SeePointsCheck"))
        self.horizontalLayout_15.addWidget(self.SeePointsCheck)
        self.DetectFreqCheck = QtGui.QCheckBox(self.groupBox_4)
        self.DetectFreqCheck.setObjectName(_fromUtf8("DetectFreqCheck"))
        self.horizontalLayout_15.addWidget(self.DetectFreqCheck)
        self.verticalLayout_2.addLayout(self.horizontalLayout_15)
        self.pushButton = QtGui.QPushButton(self.groupBox_4)
        self.pushButton.setAutoRepeatDelay(10)
        self.pushButton.setAutoRepeatInterval(10)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.verticalLayout_2.addWidget(self.pushButton)
        self.groupBox_6 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(840, 610, 161, 131))
        self.groupBox_6.setCheckable(False)
        self.groupBox_6.setChecked(False)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setContentsMargins(-1, -1, 3, -1)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.ConfSerComPortCombo = QtGui.QComboBox(self.groupBox_6)
        self.ConfSerComPortCombo.setMinimumSize(QtCore.QSize(80, 0))
        self.ConfSerComPortCombo.setObjectName(_fromUtf8("ConfSerComPortCombo"))
        self.ConfSerComPortCombo.addItem(_fromUtf8(""))
        self.horizontalLayout_17.addWidget(self.ConfSerComPortCombo)
        self.ConfSerComPortLabel = QtGui.QLabel(self.groupBox_6)
        self.ConfSerComPortLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ConfSerComPortLabel.setObjectName(_fromUtf8("ConfSerComPortLabel"))
        self.horizontalLayout_17.addWidget(self.ConfSerComPortLabel)
        self.verticalLayout_6.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setContentsMargins(-1, -1, 3, -1)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.ConfSerBaoudRateCombo = QtGui.QComboBox(self.groupBox_6)
        self.ConfSerBaoudRateCombo.setMinimumSize(QtCore.QSize(80, 0))
        self.ConfSerBaoudRateCombo.setObjectName(_fromUtf8("ConfSerBaoudRateCombo"))
        self.ConfSerBaoudRateCombo.addItem(_fromUtf8(""))
        self.horizontalLayout_18.addWidget(self.ConfSerBaoudRateCombo)
        self.ConfSerBaoudRateLabel = QtGui.QLabel(self.groupBox_6)
        self.ConfSerBaoudRateLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ConfSerBaoudRateLabel.setObjectName(_fromUtf8("ConfSerBaoudRateLabel"))
        self.horizontalLayout_18.addWidget(self.ConfSerBaoudRateLabel)
        self.verticalLayout_6.addLayout(self.horizontalLayout_18)
        self.ConfSerPowerButton = QtGui.QPushButton(self.groupBox_6)
        self.ConfSerPowerButton.setMinimumSize(QtCore.QSize(0, 31))
        self.ConfSerPowerButton.setStyleSheet(_fromUtf8("background-color: rgb(51, 255, 98);"))
        self.ConfSerPowerButton.setCheckable(True)
        self.ConfSerPowerButton.setAutoRepeatDelay(100)
        self.ConfSerPowerButton.setAutoRepeatInterval(10)
        self.ConfSerPowerButton.setObjectName(_fromUtf8("ConfSerPowerButton"))
        self.verticalLayout_6.addWidget(self.ConfSerPowerButton)
        self.splitter.raise_()
        self.line.raise_()
        self.MeterCheck.raise_()
        self.SignelGenCheck.raise_()
        self.SamplingControlsFrame.raise_()
        self.XYZCheck.raise_()
        self.groupBox_4.raise_()
        self.groupBox_6.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1015, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setMovable(False)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.menuFile.addAction(self.actionSave)
        self.menubar.addAction(self.menuFile.menuAction())
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Arduino Oscilloscope", None))
        self.Channel1GroupBox.setTitle(_translate("MainWindow", "Channel 1", None))
        self.Channel1VLabel.setText(_translate("MainWindow", "2.0 V/Div", None))
        self.Channel1MsLabel.setText(_translate("MainWindow", "10.0 ms/Div", None))
        self.Channel1MeasureButton.setText(_translate("MainWindow", "Measure", None))
        self.Channel1CurveButton.setText(_translate("MainWindow", "Curve", None))
        self.Channel1TriggerButton.setText(_translate("MainWindow", "Trigger", None))
        self.Channel2GroupBox.setTitle(_translate("MainWindow", "Channel 2", None))
        self.Channel2VLabel.setText(_translate("MainWindow", "2.0 V/Div", None))
        self.Channel2MsLabel.setText(_translate("MainWindow", "10.0 ms/Div", None))
        self.Channel2MeasureButton.setText(_translate("MainWindow", "Measure", None))
        self.Channel2CurveButton.setText(_translate("MainWindow", "Curve", None))
        self.Channel2TriggerButton.setText(_translate("MainWindow", "Trigger", None))
        self.Channel3GroupBox.setTitle(_translate("MainWindow", "Channel 3", None))
        self.Channel3VLabel.setText(_translate("MainWindow", "2.0 V/Div", None))
        self.Channel3MsLabel.setText(_translate("MainWindow", "10.0 ms/Div", None))
        self.Channel3MeasureButton.setText(_translate("MainWindow", "Measure", None))
        self.Channel3CurveButton.setText(_translate("MainWindow", "Curve", None))
        self.Channel3TriggerButton.setText(_translate("MainWindow", "Trigger", None))
        self.Channel4GroupBox.setTitle(_translate("MainWindow", "Channel 4", None))
        self.Channel4VLabel.setText(_translate("MainWindow", "2.0 V/Div", None))
        self.Channel4MsLabel.setText(_translate("MainWindow", "10.0 ms/Div", None))
        self.Channel4MeasureButton.setText(_translate("MainWindow", "Measure", None))
        self.Channel4CurveButton.setText(_translate("MainWindow", "Curve", None))
        self.Channel4TriggerButton.setText(_translate("MainWindow", "Trigger", None))
        self.MeterCheck.setTitle(_translate("MainWindow", "Meter", None))
        self.label_11.setText(_translate("MainWindow", "R :: 470 ohm (1)", None))
        self.SignelGenCheck.setTitle(_translate("MainWindow", "Signal Generator", None))
        self.SigGenFreqLabel.setText(_translate("MainWindow", "f 50.0 Hz", None))
        self.SigGenPeriodLabel.setText(_translate("MainWindow", "T 20.0 ms", None))
        self.SigGenDutyLabel.setText(_translate("MainWindow", "Duty 25%", None))
        self.SamplingControlsFrame.setTitle(_translate("MainWindow", "Sampling Contorls (100.0ms)", None))
        self.SampConrolDTLabel.setText(_translate("MainWindow", "dt 1 ms", None))
        self.SampControlQLabel.setText(_translate("MainWindow", "q 100 ", None))
        self.SamplingControlOnceButton.setText(_translate("MainWindow", "ONCE", None))
        self.SamplingControlVariousButton.setText(_translate("MainWindow", "VARIOUS", None))
        self.SamplingControlFlowButton.setText(_translate("MainWindow", "FLOW", None))
        self.XYZCheck.setTitle(_translate("MainWindow", "XYZ", None))
        self.XYZ_VDivLabel.setText(_translate("MainWindow", "2.0 V/Div", None))
        self.XYZ_ViewchannelsCheck.setText(_translate("MainWindow", "View channels", None))
        self.XYZ_SoftCurvesLabel.setText(_translate("MainWindow", "Soft Curves", None))
        self.SeePointsCheck.setText(_translate("MainWindow", "See Points", None))
        self.DetectFreqCheck.setText(_translate("MainWindow", "Detect Frequency", None))
        self.pushButton.setText(_translate("MainWindow", "Save Data", None))
        self.pushButton.setShortcut(_translate("MainWindow", "Ctrl+Shift+S", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Configure Serial", None))
        self.ConfSerComPortCombo.setItemText(0, _translate("MainWindow", "COM 3", None))
        self.ConfSerComPortLabel.setText(_translate("MainWindow", "COM Port", None))
        self.ConfSerBaoudRateCombo.setItemText(0, _translate("MainWindow", "9600", None))
        self.ConfSerBaoudRateLabel.setText(_translate("MainWindow", "Boud Rate", None))
        self.ConfSerPowerButton.setText(_translate("MainWindow", "Power ON", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))

